name: CI
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0
    
    - name: Build
      run: |
        dotnet publish -r win-x64 -c Release --no-self-contained -p:PublishDir=../publish/win-x64
        mv publish/win-x64/Kiseki.Launcher.Windows.exe publish/win-x64/Kiseki.Launcher.exe
        mv publish/win-x64/Kiseki.Launcher.Windows.pdb publish/win-x64/Kiseki.Launcher.pdb
    
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: win-x64
        path: publish/win-x64/*
  
  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tag/v')

    steps:
      - name: Download release artifacts
        uses: actions/download-artifact@v3
        with:
          path: x64
      
      - name: Rename artifacts
        run: mv x64/win-x64.zip Kiseki.Launcher-v${{ github.ref_name }}_win-x64.zip
      
      - name: Create release draft
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ github.ref_name }}
          files: Kiseki.Launcher-v${{ github.ref_name }}_win-x64.zip
          draft: true