name: CI
on: [push]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tag/v')

    steps:
    - name: Download release artifact
      uses: actions/download-artifact@v3
      with:
        name: Kiseki.Launcher.Windows (Release)
        path: win-x64
    
    - name: Rename binary
      run: mv win-x64/Kiseki.Launcher.Windows.exe Kiseki.Launcher-v${{ github.ref_name }}_win-x64.exe
    
    - name: Create release draft
      uses: softprops/action-gh-release@v1
      with:
        name: ${{ github.ref_name }}
        files: Kiseki.Launcher-v${{ github.ref_name }}_win-x64.exe
        draft: true