name: CI
on: [push]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tag/v')

    steps:
    - name: Download release artifacts
      uses: actions/download-artifact@v3
      with:
        path: x64
    
    - name: Rename artifacts
      run: mv x64/win-x64.zip Kiseki.Launcher-v${{ github.ref_name }}_win-x64.zip
    
    - name: Create release draft
      uses: softprops/action-gh-release@v1
      with:
        name: ${{ github.ref_name }}
        files: Kiseki.Launcher-v${{ github.ref_name }}_win-x64.zip
        draft: true